version: "3"
services:
  # 其他配置参考 https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi/
  nonebot:
    build: .
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./src:/app/src"
      - "./.env.prod:/app/env.prod"
      - "/data/JiBot/data:/app/data"
      - "/data/JiBot/logs:/app/logs"
    env_file:
      - ".env.prod" # fastapi 使用的环境变量文件
    environment:
      - ENVIRONMENT=prod # 配置 nonebot 运行环境，此项会被 .env 文件覆盖
      - APP_MODULE=bot:app # 配置 asgi 入口
      - MAX_WORKERS=1 # 如果你有多个QQ，且存在 self_id 指定，多个 worker 会导致无法找到其他 websocket 连接
    network_mode: bridge

  go-cqhttp:
    image: "silicer/go-cqhttp:latest"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/data/go-cqhttp/data:/data/data"
      - "/data/go-cqhttp/logs:/data/logs"
      - "/data/go-cqhttp/config.yml:/data/config.yml"
      - "/data/go-cqhttp/device.json:/data/device.json"
      - "/data/go-cqhttp/session.token:/data/sesstion.token"
    network_mode: bridge
    depends_on:
      - qsign
    links:
      - "qsign:jibot.qsign"
      - "nonebot:jibot.nonebot"

  qsign:
    image: "xzhouqd/qsign:core-1.1.7"
    volumes:
      - "/data/qsign/config.json:/srv/qsign/qsign/txlib/8.9.63/config.json"
    network_mode: bridge
    environment:
      - BASE_PATH=/srv/qsign/qsign/txlib/8.9.63