version: "3"
services:
  # 其他配置参考 https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi/
  nonebot:
    build: .
    container_name: nonebot
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./src:/app/src"
      - "./.env.prod:/app/env.prod"
      - "/data/JiBot/data:/app/data"
      - "/data/JiBot/logs:/app/logs"
    env_file:
      - ".env.prod" # fastapi 使用的环境变量文件
    environment:
      - ENVIRONMENT=prod # 配置 nonebot 运行环境，此项会被 .env 文件覆盖
      - APP_MODULE=bot:app # 配置 asgi 入口
      - MAX_WORKERS=1 # 如果你有多个QQ，且存在 self_id 指定，多个 worker 会导致无法找到其他 websocket 连接
    restart: always

  go-cqhttp:
    image: "silicer/go-cqhttp:latest"
    container_name: go-cqhttp
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/data/go-cqhttp:/data"
    depends_on:
      - qsign
    restart: always

  qsign:
    image: "xzhouqd/qsign:core-1.1.9"
    container_name: qsign
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/data/qsign/config.json:/srv/qsign/qsign/txlib/8.9.73/config.json"
    environment:
      - BASE_PATH=/srv/qsign/qsign/txlib/8.9.73
    restart: always
    
  recorder:
    image: bililive/recorder:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: /data/JiBot/data/recorder/record
        target: /rec
    ports:
      - "33333:2356"
      # 第一个 2356 是宿主机的端口，可以根据自己需求改动。
      # 第二个 2356 是容器内的端口，不要修改。
    environment:
      - BREC_HTTP_BASIC_USER=
      - BREC_HTTP_BASIC_PASS=